.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2022 Bram Stolk <b.stolk@gmail.com>,
.\"
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH DISKGRAPH 1 "September  7 2022"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
diskgraph \- program to graph disk activity
.SH SYNOPSIS
.B diskgraph /dev/nvme0n1
.SH DESCRIPTION
This manual page documents the
.B diskgraph
command.
.PP
\fBdiskgraph\fP is a program that that shows a live graph of disk activity.
.br
It shows the READ bandwidth, the WRITE bandwith and the number of operations that are in flight.
.br
.SH ARGUMENTS
The first and only parameter is a disk device like /dev/sda or /dev/nvme0n1 or similar.
.br
.SH SEE ALSO
.br
